name: CI/CD Pipeline (Deep Learning)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      # 3. Install Dependencies
      # PENTING: Saya tambahkan 'tensorflow' karena model Sense pakai Keras
      # Saya juga tambahkan 'scikit-plot' karena script visualisasi membutuhkannya
      - name: Install MLflow, DagsHub & Libraries
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn scikit-plot tensorflow imbalanced-learn

      # 4. Run MLflow Project (Training)
      - name: Run MLflow Project & Connect DagsHub Repository
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          # URL DagsHub Sense (Bukan Mo-Feb lagi)
          MLFLOW_TRACKING_URI: "https://dagshub.com/calebevan2208/SMSML_CalebAnthony.mlflow"
        run: |
          # Menjalankan project di folder Workflow-CI
          # --experiment-name HARUS SAMA dengan yang ada di script Python
          mlflow run Workflow-CI/MLProject \
            --env-manager=local \
            --experiment-name "CalebAnthony_Churn_DeepLearning_Tuning"

      # 5. Build Docker Model (Auto-Generate from Registry)
      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: "https://dagshub.com/calebevan2208/SMSML_CalebAnthony.mlflow"
        run: |
          echo "üê≥ Building Docker Image from DagsHub Registry..."
          
          # PENTING: --model-uri harus memanggil 'registered_model_name' dari script Python
          # Script Python Sense menamakan modelnya: "CalebAnthony_Churn_DeepLearning_Tuning"
          # 'latest' akan mengambil versi terakhir yang baru saja di-train di langkah sebelumnya.
          
          mlflow models build-docker \
            --model-uri "models:/CalebAnthony_Churn_DeepLearning_Tuning/latest" \
            --name "churn-dl-image" \
            --enable-mlserver

      # 6. Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Push to Docker Hub
      - name: Push to Docker Hub
        run: |
          echo "üöÄ Pushing to Docker Hub..."
          # Tagging image agar sesuai format Docker Hub (username/nama-image:tag)
          docker tag churn-dl-image ${{ secrets.DOCKERHUB_USERNAME }}/churn-deep-learning:latest
          
          # Push
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-deep-learning:latest
